name: Generate Commits

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: konradlinkowski/contributionsgenerator@master
        env:
          GITHUB_TOKEN: ${{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}}
        with:
          GIT_NAME: TheVedantKhandelwal
          GIT_EMAIL: khandelwalvedant1543@gmail.com
